### ISSUE TITLE
Question: why the menu is hard coded in menu.gsp and how to get the menu structure automated created?

### ISSUE THREAD

**Issue by aisbergde** [docToolchain/arc42-template-project#6]
The template contains `menu.gsp`, which is used in several other gsp files. it contains a hard codes menu structure.

I also want to use the microsite based on this template to replace a github wiki (github asciidoc support is too limited). And there it would be quite complex (and not compliant to doc-as-code approach) to maintain the menu structure redundantly in two places.

I also had a look at some jBake examples (for example https://github.com/jbake-org/jbake-example-project-groovy)
There is no hard coded menu in the example. And nothing about the required hard coded menu in the jBake documentation.

It seems to me that jBake might also be able to create a menu structure automatically from the `site\content` structure. Anyway, that would be logical if such a thing could be automated.

Therefore, I do not understand:
- What is the reason to hardcode the menu structure manually?
- Would it also be possible (and maybe useful) to derive the menu structure from site\content?
- How would this have to be done?

**Comment by rdmueller** [comment]
in the current version, the menu is not hardcoded anymore. It is build within the menu.gsp template and thus works different than the original jbake mechanisms. 

currently there are two way to build up the menu:

a) it can be automatically derived from the folder structure

b) you can set it through :jbake-menu: and :jbake-order: asciidoc attributes

docs will follow soon
