### ISSUE TITLE
toc is static without scrollbars. long toc are hard to use. very different view in preview and on the website

### ISSUE THREAD

**Issue by aisbergde** [docToolchain/arc42-template-project#7]
doctoolchain creates great html. The TOC contains scrollbars, icons are uses for notes and so on. Here is an example created using doctoolchain
![image](https://user-images.githubusercontent.com/9020187/111813085-08b08900-88d9-11eb-9acb-450d454aee6d.png)

But when I use these template to create a microsite, it looks not so good compared to the output generated by doctoolchain
![image](https://user-images.githubusercontent.com/9020187/111813576-a7d58080-88d9-11eb-8ba2-39d463498160.png)

- toc has no scrollbar
- fonts are not so nice
- printed area is small compared to the font size
- strange numbering (missing numbering)
- other levels (deeper levels then in doctoolchain generated file)

I have seen that this template also uses doctoolchain. That's why I think these issues could be related to the fact, that the generated site is not a solo site, but is integrated into some "context"

![image](https://user-images.githubusercontent.com/9020187/111813959-2e8a5d80-88da-11eb-8ba9-d32e6ea8bff0.png)

I think, some issues I can solve changing the CSS. And maybe I need to play with [leveloffset=0]

But in VSC preview it looks like required. But on the website it looks very different.

Preview in VSC:
![image](https://user-images.githubusercontent.com/9020187/111814665-07805b80-88db-11eb-91e4-f79b1377145e.png)

- toc is OK
  - existing numbering
  - existing scrollbar
- missing icon for NOTE (but this is OK in the preview)

**Comment by rdmueller** [comment]
Sorry, I haven't seen this issue before. Just read your excellent blogpost with so much feedack. Thanx for writing it!

I think the style made some progress but I will double check with this issue soon.

**Comment by rdmueller** [comment]
Wow. Just noticed my comment below your article. So I've seen it before :-o

**Comment by rdmueller** [comment]
So, with the latest release of doctoolchain, we released a new standard theme: Docsy
And I think it looks way better than the old standard twitter bootstrap theme:
http://doctoolchain.org/docToolchain/v2.0.x/015_tasks/03_tasks.html

Scrollbar and fonts should be ok.

Some things like the admonition icon and the heading numbering is configured as attribute directly in asciidoc...

**Comment by rdmueller** [comment]
Wow. I just noticed that I was soooo wrong with my first comment. I even discussed those other issues with you but wasn't aware of it anymore. I guess I am getting old - sorry for that

**Comment by aisbergde** [comment]
Schrollbar and fonts should be OK now. Now with the scrollbar in ToC I don't need to recommend any special static site generator to create a personal website if someone asks me.

For my database documentation generator, I use Antora, and I am happy with this solution, because often 1000+ pages are created, the content is created automatically (exported from databases in the required way). Antora has components, modules, a virtual file system, multiple repository support, very new: a lunr search extension. Antora is great for enterprise documentation. But it is oversized and hard to explain if someone just wants to build a website, content from various sources should be integrated, not caring about a specific folder structure to organize the content. In this case docToolchain is much easier to use. To be able to promote Asciidoc and Docs-as-Code docToolchain is great!

**Comment by rdmueller** [comment]
I already think about sopport for antora in docToolchain as a second renderer. My main problem with Antora is that it needs node and only supports AsciiDoc. In a corporate environment, I have lots of teams who need other markup languages like markdown and restructured text.
But thanx again for your detailed feedback. I will try to incorporate it into docToolchain soon.

I hope it is ok if I close this issue now.

**Comment by aisbergde** [comment]
>In a corporate environment, I have lots of teams who need other markup languages like markdown and restructured text.

Yes, this is a hard limit, and the strong folder structure, and node, ... It is not so easy to promote Antora. To promote docToolchain for Docs-as-Code should be easier.
