### ISSUE TITLE
doctoolchain version 1.2.0 is hard coded, how to manage the version on the netlify build server?

### ISSUE THREAD

**Issue by aisbergde** [docToolchain/arc42-template-project#8]
in dtcw is hard coded that an old version of doctoolchain should be installed (docToolchain-1.2.0), if it is missing.

On my local PC I can install a newer version.

But the build happens on the netlify server
- How to know which version is used by the netlify build server?
- If this script installed the very old version of doctoolchain on netlify, how to install a newer version there?
- how to manage the doctoolchain version on netlify?

**Comment by rdmueller** [comment]
the version is currently configured in dtcw and it is updated to 2.0.3. So I guess this issue is ourdated. Sorry that it took so long to reply
